version: '3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=culturameta_db
      - POSTGRES_USER=culturameta
      - POSTGRES_PASSWORD=CultuR4M3t4
  mogi:
    build: .
    container_name: mogi
    ports:
      - 8002
    volumes:
      - .:/code-electronicstamp
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - database
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'mogi.vueanalytic.com -> http://mogi:8002'
      STAGE: 'production' # Don't use production until staging works
      CLIENT_MAX_BODY_SIZE:  5M
    volumes:
      - https-portal-data:/var/lib/https-portal
      - /data/https-portal/vhosts:/var/www/vhosts
    depends_on:
      - mogi
volumes:
    https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL