# Generated by Django 4.2.10 on 2024-02-13 19:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('campo1', models.CharField(blank=True, help_text='campo1', max_length=300, null=True, verbose_name='campo1')),
                ('campo2', models.CharField(blank=True, help_text='campo2', max_length=300, null=True, verbose_name='campo2')),
                ('month', models.CharField(blank=True, help_text='redirigir', max_length=300, null=True, verbose_name='redirigir')),
                ('orden', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True, verbose_name='Estado:')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('formato', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=30, null=True, verbose_name='Estado:')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(blank=True, choices=[('PRINCIPAL', 'PRINCIPAL'), ('SECUNDARIO', 'SECUNDARIO')], max_length=30, null=True, verbose_name='Estado:')),
                ('orden', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True, verbose_name='Estado:')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('Slider',),
                'verbose_name_plural': 'Slider',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(blank=True, help_text='Menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.menu', verbose_name='Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre ', max_length=100, verbose_name='Nombre ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/documento', verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(blank=True, help_text='pagina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.pagina', verbose_name='pagina')),
            ],
            options={
                'verbose_name': ('Documento',),
                'verbose_name_plural': 'Documento',
                'ordering': ['id'],
            },
        ),
    ]
