# Generated by Django 4.2.16 on 2024-10-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_pagina_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('consecutive', models.IntegerField()),
                ('contract_number', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=255)),
                ('object', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='configuracion.contract'),
        ),
    ]
