# Generated by Django 4.2.16 on 2024-10-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_contract_alter_document_options_document_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contract',
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='configuracion.contract')),
            ],
        ),
    ]
